### ISSUE TITLE
Error: Setting up fake worker failed: "No "GlobalWorkerOptions.workerSrc" specified."."

### ISSUE THREAD

**Issue by marcelpanse** [opengovsg/pdf2md#64]
When running pdf2md from Node I get this error:
`Error: Setting up fake worker failed: \"No \"GlobalWorkerOptions.workerSrc\" specified.\"."`

- OSX Ventura (Apple silicon)
- Node 18.15.0

Adding this line fixes the problem for me:
`pdfjs.GlobalWorkerOptions.workerSrc = `pdfjs-dist/legacy/build/pdf.worker`;`
in `lib/util/pdf.js` fixes the problem for me.

I'm not familiar with pdf.js so I have no idea if this is the correct approach/solution.

**Comment by LoneRifle** [comment]
Related to mozilla/pdf.js#10478
