### ISSUE TITLE
Top-level await is currently not supported with the "cjs" output format in 0.1.31

### ISSUE THREAD

**Issue by Kirksten3** [opengovsg/pdf2md#86]
**Describe the bug**
We upgraded from 0.1.29 -> 0.1.31 and we're getting build esbuild failures now. The error is as in the title:
```
node_modules/pdfjs-dist/build/pdf.mjs:19764:53: ERROR: Top-level await is currently not supported with the "cjs" output format
```

It looks like the offending line in `pdf.mjs` is:
```
/******/ __webpack_exports__ = globalThis.pdfjsLib = await (globalThis.pdfjsLibPromise = __webpack_exports__);
```

Looks like there was an import change in between these versions but I'm not quite sure what the cause might be.

**Desktop (please complete the following information):**
 - OS: Sonoma 14.4.1
 - Mac m1

**Comment by LoneRifle** [comment]
Thanks for spotting this! The cause for the problem is due to 39e5f04, in response to a high-severity security alert, which upgraded pdfjs-dist to a version that migrated to esm modules. You may have to consult your build documentation to figure out how to work with such modules. Hope that helps!

**Comment by Kirksten3** [comment]
Thanks for the response - I believe we have something in the works for it.
