### ISSUE TITLE
Patch update was a breaking change - requires node 22

### ISSUE THREAD

**Issue by abrenneke** [opengovsg/pdf2md#87]
**Describe the bug**
The [change here](https://github.com/opengovsg/pdf2md/commit/767ffcc6829ca896b56caae004310c5e23c8d02e) switched from `pdfjs-dist/legacy/build` to `pdfjs-dist/build`. The non-legacy import uses `Promise.withResolvers`, which is only supported in [Node 22+](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/withResolvers#browser_compatibility).

We have a case where a lockfile isn't used, so the new version was automatically pulled in and stopped working because it uses Node 18 :(

**To Reproduce**
1. Try to run latest version of the library in Node 18 or 20.

**Expected behavior**
Works

**Comment by sarve-shreyas** [comment]
Does anyone have fix for this ?

**Comment by tonisives** [comment]
You can use the older version: `"@opendocsg/pdf2md": "0.1.29",`
