### ISSUE TITLE
Node.js version

### ISSUE THREAD

**Issue by aarontimo** [opengovsg/pdf2md#88]
**Describe the bug**
Does this package have any specific requirements or compatibility regarding the Node.js version? I am using Node.js v20.12.2. When I run
`npx @opendocsg/pdf2md --inputFolderPath=/Users/u8008006/pdf2md_input --outputFolderPath=/Users/u8008006/pdf2md_output`

I get the following error:

```
TypeError: Promise.withResolvers is not a function
    at file:///Users/u8008006/node_modules/pdfjs-dist/build/pdf.mjs:5300:35
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
TypeError: Promise.withResolvers is not a function
    at file:///Users/u8008006/node_modules/pdfjs-dist/build/pdf.mjs:5300:35
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

TypeError: Promise.withResolvers is not a function
    at file:///Users/u8008006/node_modules/pdfjs-dist/build/pdf.mjs:5300:35
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)

Node.js v20.12.2
``` 

**Desktop (please complete the following information):**
 - OS: Montenary 12.6
 - Browser: Chrome
 - Version 125.0.6422.142 (Official Build) (arm64)

**Additional context**
The above command used to work for me. I had to uninstall and reinstall Java recently...not sure if this would be relevant.

**Comment by LoneRifle** [comment]
Promise.withResolvers is available on Node 22, so you may wish to use that version instead. If you wish, you may file a PR to pdf2md that adds an [engines](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#engines) param, to help better determine whether pdf2md can be used in a given environment.

**Comment by aarontimo** [comment]
Thank you @LoneRifle - using Node 22 worked! Thank you for your help.
