### ISSUE TITLE
[Bug] The new version 0.1.32 try find a non-existing file by running the resolve the pdf.js

### ISSUE THREAD

**Issue by whats2000** [opengovsg/pdf2md#94]
**Describe the bug**
That happens after upgrading to 0.1.32, it seems there are some incapable issues for node 20
It seems the package is trying to find a non-existing file by running the resolve the pdf.js
```
node_modules\pdfjs-dist\legacy\build\pdf doesn't exist
node_modules\pdfjs-dist\legacy\build\pdf.js doesn't exist
node_modules\pdfjs-dist\legacy\build\pdf.ts doesn't exist
```

**To Reproduce**
1. Go to terminal
2. Run the npm build with the package update to 0.1.32
3. Invoke error and build fail

**Expected behavior**
Build without any error

**Screenshots**
![image](https://github.com/user-attachments/assets/4b89f710-b9e6-4134-bfe5-37058e451eda)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser VSCode
 - Node Version v20.16.0 
 - Package Version 0.1.32

**Comment by LoneRifle** [comment]
Please try this with v0.2.0 of this package, which removes the dependency on node-specific libs, including `path`.

**Comment by whats2000** [comment]
What's a great news!

**Comment by LoneRifle** [comment]
@whats2000 please close this issue if this has been resolved for you
