### ISSUE TITLE
Add unpdf for cloudflare support - pdfjs-dist gives ERRORS 

### ISSUE THREAD

**Issue by vtempest** [opengovsg/pdf2md#95]
https://airesearch.js.org/functions/convertPDFToHTML.html
Adds footnote and headings.

https://github.com/johannschopplich/pdfjs-serverless
It is better bc it supports more environemnts.

Current version wont compile, error Cannot find pdfjs-dist build

Added PR: https://github.com/opengovsg/pdf2md/pull/96/files

**Comment by LoneRifle** [comment]
Fixed by #96
